set ASBUILDER_HOME=D:\ASBuilder
set ANT_HOME_BASE=D:\ASBuilder\ant-1.8.2
set SVN_TOOL_BASE=C:\Program Files\SlikSvn\bin
set JAVA_HOME_BASE=C:\Program Files (x86)\Java\jdk1.6.0_21\bin
set path=%path%;%ASBUILDER_HOME%\libs\;
set path=%path%;%ASBUILDER_HOME%\libs\mims-core.jar;%ASBUILDER_HOME%\libs\mims-swing.jar;%ANT_HOME_BASE%\bin;%SVN_TOOL_BASE%;%ASBUILDER_HOME%\libs\e1-asbuilder-1.1.jar;%JAVA_HOME_BASE%;%ASBUILDER_HOME%\libs\sqlite-jdbc-3.7.15-SNAPSHOT.jar;%ASBUILDER_HOME%\libs\log4j.jar;%ASBUILDER_HOME%\libs\e1asbuiler_server.jar
set classpath=.;%ASBUILDER_HOME%\libs\e1-asbuilder-1.1.jar;%ASBUILDER_HOME%\libs\sqlite-jdbc-3.7.15-SNAPSHOT.jar;%ASBUILDER_HOME%\libs\log4j.jar;%ASBUILDER_HOME%\libs\e1asbuiler_server.jar;%ASBUILDER_HOME%\libs\mims-core.jar;%ASBUILDER_HOME%\libs\mims-swing.jar;
set path=%path%;%ASBUILDER_HOME%\libs\commons-beanutils-1.9.0.jar;%ASBUILDER_HOME%\libs\commons-collections-3.2.1.jar;%ASBUILDER_HOME%\libs\commons-lang-2.6.jar;%ASBUILDER_HOME%\libs\flex-messaging-common.jar;%ASBUILDER_HOME%\libs\flex-messaging-core.jar;
set path=%path%;%ASBUILDER_HOME%\libs\commons-logging-1.1.3.jar;%ASBUILDER_HOME%\libs\ezmorph-1.0.6.jar;%ASBUILDER_HOME%\libs\json-lib-2.4-jdk15.jar;%ASBUILDER_HOME%\libs\e1_lzma.jar;
set path=%path%;%ASBUILDER_HOME%\libs\ngcod-encrypt.jar;%ASBUILDER_HOME%\libs\ngcod-file.jar;%ASBUILDER_HOME%\libs\ngcod-lzma.jar;
set path=%path%;%ASBUILDER_HOME%\libs\ngcod-dmp.jar;%ASBUILDER_HOME%\libs\ngcod-log.jar;
set path=%path%;%ASBUILDER_HOME%\libs\activation.jar;%ASBUILDER_HOME%\libs\mail.jar;%ASBUILDER_HOME%\libs\commons-email-1.2.jar;

set classpath=%classpath%;%ASBUILDER_HOME%\libs\
set classpath=%classpath%;%ASBUILDER_HOME%\libs\ngcod-encrypt.jar;%ASBUILDER_HOME%\libs\ngcod-file.jar;%ASBUILDER_HOME%\libs\ngcod-lzma.jar;
set classpath=%classpath%;%ASBUILDER_HOME%\libs\ngcod-dmp.jar;%ASBUILDER_HOME%\libs\ngcod-log.jar
set classpath=%classpath%;%ASBUILDER_HOME%\libs\commons-beanutils-1.9.0.jar;%ASBUILDER_HOME%\libs\commons-collections-3.2.1.jar;%ASBUILDER_HOME%\libs\commons-lang-2.6.jar;%ASBUILDER_HOME%\libs\flex-messaging-common.jar;%ASBUILDER_HOME%\libs\flex-messaging-core.jar;
set classpath=%classpath%;%ASBUILDER_HOME%\libs\commons-logging-1.1.3.jar;%ASBUILDER_HOME%\libs\ezmorph-1.0.6.jar;%ASBUILDER_HOME%\libs\json-lib-2.4-jdk15.jar;
set classpath=%classpath%;%ASBUILDER_HOME%\libs\activation.jar;%ASBUILDER_HOME%\libs\mail.jar;%ASBUILDER_HOME%\libs\commons-email-1.2.jar;